version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      # set up a mongodb container
      - run:
          name: Set up MongoDB container
          command: docker run -p 27017:27017 --name mongo_example -d mongo

      # run flask test
      - run:
          name: Run Pytest
          command: pytest
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests
