version: 2.1
services:
  mongo:
    image: mongo:latest
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - my-network
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      # check docker veresion, make sure that docker is running
      - run:
          name: Check Docker version
          command: docker --version

      # Set up Docker Network
      - run:
          name: Set up Docker Network
          command: docker network create my-network

      # set up a mongodb container
      - run:
          name: Set up MongoDB container
          command: |
            docker run -p 27017:27017 --name mongo-example --network my-network -d mongo

      - run:
        name: run flask app container
        command: |
          docker run -p 3000:3000 --network my-network flask-rest-docker-app-hw1:1.0

      # run flask test
      - run:
          name: Run Pytest
          command: pytest
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests
