version: 2.1 # allows you access to latest features
workflows:
  test-deploy:
    jobs:
      - test
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.9.18
    steps:
      - checkout
      - run:
        node --version
#       - run:
#         name: Install Python dependencies
#         command: |
#         conda activate notes-app-env
#         pip install -r requirements.txt
#       - run:
#           name: Run unit test
#           command: |
#           pytest tests/test_endpoints.py
#       - store_test_results:
#           path: test-reports
#       - store_artifacts:
#           path: test-reports
# workflows:
#   build_test:
#     jobs:
#       - run_tests