version: 2.1
services:
  mongo:
    image: mongo:latest
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - my-network
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      # run flask test
      - run:
          name: Run Pytest
          command: pytest
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests
